create table StuInfo(
RegNo int,
SName varchar(15),
FName varchar(15),
MName varchar(15),
DOB date,
Age tinyInt,
Gender varchar,
Nationality varchar(15),
Category varchar(6),
Addrs1 varchar(20),
Addrs2 varchar(20),
City varchar(10),
Pincode int,
Phone bigint,
Email varchar(25),
Aadhar bigint,
EMIS varchar(15))